// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: booky.proto

package booky

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookyServiceClient is the client API for BookyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookyServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type bookyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookyServiceClient(cc grpc.ClientConnInterface) BookyServiceClient {
	return &bookyServiceClient{cc}
}

func (c *bookyServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/booky.BookyService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookyServiceServer is the server API for BookyService service.
// All implementations must embed UnimplementedBookyServiceServer
// for forward compatibility
type BookyServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedBookyServiceServer()
}

// UnimplementedBookyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookyServiceServer struct {
}

func (UnimplementedBookyServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedBookyServiceServer) mustEmbedUnimplementedBookyServiceServer() {}

// UnsafeBookyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookyServiceServer will
// result in compilation errors.
type UnsafeBookyServiceServer interface {
	mustEmbedUnimplementedBookyServiceServer()
}

func RegisterBookyServiceServer(s grpc.ServiceRegistrar, srv BookyServiceServer) {
	s.RegisterService(&BookyService_ServiceDesc, srv)
}

func _BookyService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookyServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booky.BookyService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookyServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookyService_ServiceDesc is the grpc.ServiceDesc for BookyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booky.BookyService",
	HandlerType: (*BookyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _BookyService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booky.proto",
}
