name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to cloud evolution artifact registry
      uses: docker/login-action@v1
      with:
        registry: ${{vars.REGESTRY_ADDRESS}}
        username: ${{secrets.KEY_ID}}
        password: ${{secrets.KEY_SECRET}}
    - name: Build and push container image to cloud evolution registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{vars.REGESTRY_ADDRESS}}/booky:latest
        file: ./Dockerfile
        context: ./
      
